SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 32
  BASE_LR: 0.02
  STEPS: (19200, 25600)
  MAX_ITER: 32000
  WEIGHT_DECAY: 0.0001
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
TEST:
  VISIBILITY_THRES: 0.33333333
  TRUNCATION_THRES: 0.33333333
  EVAL_PERIOD: 16000
DATASETS:
  TRAIN: ('KITTI_train', 'KITTI_val')
  TEST: ('KITTI_test',) 
  CATEGORY_NAMES: ('pedestrian', 'car', 'cyclist', 'van', 'truck', 'tram', 'person')
  IGNORE_NAMES: "['dontcare', 'ignore', 'void']"
  MIN_HEIGHT_THRES: 0.05
  TRUNCATION_THRES: 0.75
  VISIBILITY_THRES: 0.25
  TRUNC_2D_BOXES: True
VIS_PERIOD: 640
DATALOADER:
  SAMPLER_TRAIN: "RepeatFactorTrainingSampler"
  REPEAT_THRESHOLD: 0.1
MODEL:
  PIXEL_MEAN: [103.530, 116.280, 123.675]
  PIXEL_STD: [57.375, 57.120, 58.395]
  STABILIZE: 0.02
  USE_BN: True
  META_ARCHITECTURE: "Omni3DFormer"
VERSION: 2