_BASE_: "Base.yaml"

DATASETS:
  TRAIN: ('nuScenes_train', 'nuScenes_val', 'KITTI_train', 'KITTI_val')
  #TRAIN: ('SUNRGBD_val',)
  TEST: ('KITTI_test', 'nuScenes_test')
  #TEST: ('SUNRGBD_val',)
  CATEGORY_NAMES: ('cyclist', 'pedestrian', 'trailer', 'bus', 'motorcycle', 'car', 'barrier', 'truck', 'van', 'traffic cone', 'bicycle')

INPUT:
  RESIZE_TGT_SIZE: (640, 512)
  RANDOM_FLIP: "none"
  COLOR_AUG: True

SOLVER:
  IMS_PER_BATCH: 64
  TYPE: "mmcv_AdamW"
  BASE_LR: 4e-4
  WEIGHT_DECAY: 1e-2
  MAX_ITER: 87000
  VIRTUAL_EPOCHS: 20
  VIRTUAL_LOSS: 5.0   # To avoid the total loss is too small.

  LR_SCHEDULER_NAME: "CosineAnnealing"
  WARMUP_FACTOR: 0.3333
  WARMUP_ITERS: 500
  WARMUP_METHOD: "linear"

  CLIP_GRADIENTS: 
    ENABLED: True
    CLIP_VALUE: 35.0
    NORM_TYPE: 2.0

TEST:
  EVAL_PERIOD: 17400
  EVAL_MODE: 'DAP3D' # 'ALL_PRED' or 'GT_LOC' or 'GT_POSEDIM' or 'DAP3D'

MODEL:
  META_ARCHITECTURE: "Omni3DFormer"

  DETECTOR3D:
    DETECT_ARCHITECTURE: "transformer"

    TRANSFORMER_DETECTOR:
      GRID_MASK: False

      BACKBONE_NAME: 'ConvNext_Base'
      BACKBONE_FP16: False
      NECK_NAME: 'SECONDFPN'
      PTS_VOXEL_NAME: 'SPConvVoxelization'
      PTS_VOXEL_ENCODER: "HardSimpleVFE"
      PTS_MIDDLE_ENCODER: "SparseEncoder"
      PTS_BACKBONE: "SECOND"
      PTS_NECK: "SECONDFPN"
      TRANSFORMER_NAME: 'DEFORMABLE_TRANSFORMER'
      TRANSFORMER_DROPOUT: 0.1
      MATCHER_NAME: 'HungarianAssigner3D'
      NUM_QUERY: 200
      FEAT_LEVEL_IDXS: ('stage2', 'stage3', 'stage4', 'stage5')
      DOWNSAMPLE_FACTOR: 16
      LLS_SPARSE: 1e-3
      NAIVE_DEPTH_HEAD: False

      MUTUAL_INFO_INPAINT: True
      PTS_PAINT_CAM: True
      CAM_PAINT_PTS: True
      LLS_SPARSE: 5e-4

      HEAD:
        UNCERN_RANGE: [-10, 10]
        CLS_WEIGHT: 2.0
        LOC_WEIGHT: 0.25
        DIM_WEIGHT: 0.25
        POSE_WEIGHT: 0.25
        DEPTH_HEAD_WEIGHT: 1.0

        ENC_NUM: 1
        DEC_NUM: 6

        POSITION_RANGE: [-30, 30, -40, 40, 0, 80]
        GRID_SIZE: [1, 80, 1]
        D_BOUND: [0.1, 100, 1]
        ENC_CAM_INTRINSIC: True 

      POST_PROCESS:
        CONFIDENCE_2D_THRE: 0.0
        CONFIDENCE_3D_THRE: -1.0
        OUTPUT_CONFIDENCE: '3D'